apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis
  name: redis
  namespace: default
spec:
  type: ExternalName
  externalName: redis.192.168.33.101.nip.io
  ports:
    - name: redis
      port: 6379
      protocol: TCP
